;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   dv. set. 18 2026
; Processor: PIC18F45K22
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p18f45k22.inc                ; Include register definition file

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
      ; Banco 15 para ANSEL
      movlb 0x0F
      
      ; Configura puertos como digitales
      clrf ANSELB, BANKED
      clrf ANSELC, BANKED
      
      ; RB0 -> entrada(boton)
      bsf TRISB, 0, ACCESS
      ; RC6 -> salida(LED)
      bcf TRISC, 6, ACCESS
      ; LED (inicialmente apagado)
      bcf LATC, 6, ACCESS
      
Loop  
      btfsc PORTB, 0, ACCESS
      goto LED_ON
      goto LED_OFF
      
LED_ON
      bsf LATC, 6, ACCESS; Sortida LED a 1
      goto  Loop
LED_OFF
      bcf LATC, 6, ACCESS; Sortida LED a 0
      goto  Loop
      

;====================================================================
      END
