;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Sep 23 2026
; Processor: PIC18F45K22
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p18f45k22.inc                ; Include register definition file
config FOSC = HSHP ; Oscillator

;====================================================================
; VARIABLES
;====================================================================
max equ D'100' ; assembler directive stating that max is number 100
counter set 0x20 ; define an assembler variable located at hexadecimal 0x20

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start

;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code
Start
   movlb 0x0F ;sel bank F in BSR to access registers not in Access Bank. Only registers placed between 0xF60 and 0xFFF are mapped in the access bank
   clrf ANSELA,BANKED ;port A digital (note that ANSELA is located at H'0F38', outside the [0xF60,0xFFF] range)
   clrf ANSELB,BANKED ;port B digital
   clrf ANSELC,BANKED ;port C digital

   clrf ANSELD, BANKED ; port d digital
   movlw b'11000000'
   movwf TRISD
   
Loop

iff
   BTFSC PORTD, 6
   BTFSS PORTD, 7
   GOTO elsee
      BSF LATD, 5
      GOTO fi_if
elsee
      BCF LATD, 5
fi_if

   MOVLW d'16' ; 1c
   MOVWF counter ; 1c
   
bucle
   DECFSZ counter ; 1c (última iteració són 3c) 
   GOTO bucle ; 2c
   
   BTG LATD, 4
   
   goto Loop   
;====================================================================
      END
